language: python
python:
        - 3.6
        - 3.5
matrix:
        include:
                - python: 3.5
                - python: 3.6
                - python: 3.7
                  dist: xenial
                  sudo: true

before_install:
        - echo "Starting the installation..."
install:
        - pip install -r requirements.txt
        - pip install -e .
before_script:
        - echo "Starting script..."
script:
        - pytest
after_success:
        - echo "Success!"
after_failure:
        - echo "Failed :("
after_script:
        - echo "Script finished."

