language: python
python:
  - '3.6'
  - '3.5'
before_install: echo "Starting the installation..."
install:
  - pip install -r requirements.txt
before_script: echo "Starting script..."
script:
  - pytest
after_success: echo "Success!"
after_failure: echo "Failed :("
after_script: echo "Script finished."

